DROP TABLE IF EXISTS favMovie;

CREATE TABLE IF NOT EXISTS favMovie (
    adult BOOLEAN,
    backdrop_path VARCHAR(255),
    belongs_to_collection VARCHAR(255),
    budget INTEGER,
    genres VARCHAR(255),
    
    homepage VARCHAR(10000),
    id INTEGER,
    imdb_id VARCHAR(10000),
   original_language VARCHAR(10000),
   original_title VARCHAR(10000),

   overview VARCHAR(10000),
   popularity FLOAT,
  poster_path  VARCHAR(10000),
   production_companies VARCHAR(10000),
   production_countries VARCHAR(10000),

   release_date VARCHAR(10000),
   revenue INTEGER,
    runtime INTEGER,
    spoken_languages VARCHAR(10000),
    status VARCHAR(10000),
    
    tagline VARCHAR(10000),
    title VARCHAR(10000),  
    video BOOLEAN
    vote_average FLOAT,
    vote_count INTEGER
 
);
/* serial : autogenerated 
     PRIMARY KEY:unique (must exist)
*/