DROP TABLE IF EXISTS favMovie;

CREATE TABLE IF NOT EXISTS favmovie(
   
  
    id  SERIAL PRIMARY KEY,
   overview VARCHAR(10000),
  
   poster_path  VARCHAR(10000),
   
   release_date VARCHAR(10000),
    
   title VARCHAR(10000),  
   comment  VARCHAR(10000)
 
);
/* serial : autogenerated 
     PRIMARY KEY:unique (must exist)
     SERIAL PRIMARY KEY,
*/